.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "V8BOINC\-TROUBLE" "7" "September 2014" "" ""
.
.SH "NAME"
\fBv8boinc-trouble\fR \-\- User manual
.
.SH "TROUBLESHOOT"
.
.IP "\(bu" 4
There is a folder \fB\|\.v8boinc\fR which is created on \fBv8boinc init\fR command\. You
can erase it at any time and re\-init to restart the project\. If anything should
go wrong this is the first thing to try\.
.
.IP "\(bu" 4
There is a \fB\|\.v8boinc/bin/jstest\fR executable\. You can create a slot directory
and link \fBjstest\fR, \fBmain\.js\fR and \fBin\.json\fR files in it to run \fBjstest\fR and see
the results manualy\.
.
.IP "" 0
